### ISSUE TITLE
Formatting problem

### ISSUE THREAD

**Issue by ccolliga** [sfu-dhil/wilde#118]
**Describe the bug**
Text of the news article is not correctly aligned. 

**To Reproduce**
Click on 'https://dhil.lib.sfu.ca/wilde/view.html?f=ea_1665
See misaligned text.

**Expected behavior**
The body text should be aligned.

**Screenshots**

<img width="984" alt="Capture d’écran, le 2021-04-02 à 10 05 59" src="https://user-images.githubusercontent.com/62541441/113437438-6d6ce880-939b-11eb-9ff1-ce45e97a6597.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mojave 10.14.6
 - Browser [e.g. chrome, safari] Chrome

Note that I am seeing similar problems on some other pages.

**Comment by joeytakeda** [comment]
This seems to be an issue with the source encoding and not the styling—that paragraph isn't wrapped in a `<p>`:

```
   <p class="heading" id="ea_1665_0">Dépêches particilières <br />de l'EXPRESS</p> 
   <p id="ea_1665_1">[...]</p> Londres, 6 avril. M. Oscar Wilde a été arrêté dans la soirée d'hier. 
   <p id="ea_1665_2">[...]</p> 
```

Since it's not in a paragraph tag, it's not being rendered as paragraph by the application (and I would imagine that would mean those untagged parts aren't being captured by the text matching program either, but @ubermichael would know for sure).

It seems that there are a handful of documents that have this issue; I'll post that list with the reports.

**Comment by joeytakeda** [comment]
Closing this and the related issues now since this is a data issue; I've opened a ticket in the reports repo now.
