### ISSUE TITLE
Supply a mechanism that lets users know which version of the data or which version of a report they are consulting (e.g., “Data was updated on xx/xx/xxxx")

### ISSUE THREAD

**Issue by rcastong** [sfu-dhil/wilde#38]

**Comment by ubermichael** [comment]
This is complete. See the screen shot. The field is blank because I do not remember when I updated the files. The next time they are updated the field will be automatically filled.

![Screen Shot 2020-03-23 at 9 55 44 AM](https://user-images.githubusercontent.com/1328893/77341864-966c8f00-6cec-11ea-9b6f-e4b0e76173d5.png)
