### ISSUE TITLE
Assist with use of Gallica and RetroNews API to collect new files

### ISSUE THREAD

**Issue by rcastong** [sfu-dhil/wilde#39]
Chronicling America: https://chroniclingamerica.loc.gov/about/api/

Trove: https://help.nla.gov.au/trove/building-with-trove/api

Gallica: http://api.bnf.fr/api-document-de-gallica

**Comment by joeytakeda** [comment]
One thing we talked about is if we need the API scraping to happen at user request (i.e. as things are found, they should be downloaded, then edited, rather than download them all at once), then we might consider doing something via a build file and use oXygen. I've done this before here: https://github.com/winnifredeatonarchive/wea_data/blob/master/data/addTextFromDrive.xml. It uses an oXygen author CSS stylesheet and special instructions so that when an encoder opens up the page, they just get a nicely formatted page with fillable fields. Once those fields are filled in, they press the Red play button in oXygen and it creates the text for them and puts it in the proper folder.

**Comment by ubermichael** [comment]
Trove and Chronicling America are done now. I can't read the French API documentation, so I don't think that's really a possibility. Closing for now.
